[package]
name = "keytan"
version = "0.0.1"
edition = "2021"

[dependencies]
chrono = "0.4.39"
crossterm = "0.28.1"
ratatui = { version = "0.29.0", features = ["unstable-rendered-line-info"] }
tui-widget-list = "0.13.2"

[profile.release]
lto = true
strip = "symbols"
